# Generated by Django 5.0.1 on 2024-03-25 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(default='default.jpeg', null=True, upload_to='cat_images')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(max_length=500, null=True)),
                ('image', models.ImageField(default='default.jpeg', null=True, upload_to='images/')),
                ('category', models.CharField(choices=[('gear less', 'Gear less'), ('gear', 'Gear')], max_length=200, null=True)),
                ('bike_ownership_count', models.PositiveIntegerField()),
                ('fuelType_object', models.CharField(choices=[('petrol', 'petrol'), ('EV', 'EV')], max_length=200)),
                ('registrationyear_object', models.PositiveIntegerField()),
                ('enginepower_cc', models.PositiveIntegerField()),
                ('sale_status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('brand_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesapp.bikebrand')),
                ('city_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='salesapp.city')),
                ('state_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='salesapp.state')),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, null=True)),
                ('message', models.TextField(max_length=3000000000)),
                ('reply', models.TextField(max_length=3000000000, null=True)),
                ('bike_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesapp.bike')),
                ('user_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user_object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saved', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WishListItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bike_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saveditems', to='salesapp.bike')),
                ('wishlist_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesapp.wishlist')),
            ],
        ),
    ]
