# Generated by Django 5.0.1 on 2024-03-29 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0003_bike_tag_object_alter_bike_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='tag_object',
        ),
    ]
