# Generated by Django 5.0.1 on 2024-03-31 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0005_bike_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='km_driven',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
