# Generated by Django 5.0.1 on 2024-03-31 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0006_bike_km_driven'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='km_driven',
            new_name='kms_driven',
        ),
    ]
