# Generated by Django 5.0.1 on 2024-04-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0007_rename_km_driven_bike_kms_driven'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='is_read',
            new_name='is_replied',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='reply',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField(max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('enquiry_obj', models.ManyToManyField(to='salesapp.enquiry')),
            ],
        ),
    ]
