# Generated by Django 5.0.1 on 2024-04-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0009_enquiry_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='is_read',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
