# Generated by Django 5.0.1 on 2024-04-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0010_reply_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='reply',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
