# Generated by Django 5.0.1 on 2024-04-07 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0011_enquiry_reply_delete_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitems',
            name='bike_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesapp.bike'),
        ),
        migrations.AlterField(
            model_name='wishlistitems',
            name='wishlist_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saveditem', to='salesapp.wishlist'),
        ),
    ]
